name: to_arabic_number
description: A Dart package to convert numbers within a string to Arabic numerals.
version: 1.0.1
repository: https://github.com/msx-git/to_arabic_number
homepage: https://github.com/msx-git/to_arabic_number

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
